- hosts: localhost
  become: true
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      update_cache: true
      upgrade: "yes"
  tasks:
    - name: Install zsh
      apt: name=zsh
      tags: zsh

    - name: Install omzsh
      shell: sh -c "$(curl -fsSL https://install.ohmyz.sh/)"
      tags: zsh

    - name: default zsh
      shell: chsh -s 'which zsh'
      tags: zsh

    - name: clone dotfiles
      shell: git clone https://github.com/pibouill/dotfiles.git ~/.config/dotfiles

    - name: Install node
      apt:
        name: ['nodejs', 'npm']
    #- name: Install cargo
    #  apt:
    #    name: cargo
